repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: Lint YAML files
        args: [--strict]
{% if cookiecutter.use_docker  %}

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
{% endif %}

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        name: Lint Markdown files
        args: ["--fix", "--config", ".markdownlint.json"]
        exclude: ^(node_modules|\.venv|\.claude|.*/_build)/

  - repo: local
    hooks:
      - id: security-bandit
        name: Security Check (Bandit)
        entry: make security
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: lint-ruff
        name: Lint and Format Check (Ruff)
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: type-mypy
        name: Type Check (MyPy)
        entry: make typecheck
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: unit-test
        name: Unit Tests (PyTest)
        entry: make test
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.19
    hooks:
      - id: uv-lock
